# Generated by Django 5.2.8 on 2025-11-26 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_parametrosistema'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Categoria de Cliente',
                'verbose_name_plural': 'Categorias de Clientes',
            },
        ),
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('CLI', 'Cliente / Sócio / Aluno'), ('FOR', 'Fornecedor'), ('AMB', 'Ambos')], default='CLI', max_length=3, verbose_name='Tipo de Cadastro')),
                ('tipo_pessoa', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PF', max_length=2)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome / Nome Fantasia')),
                ('razao_social', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razão Social (PJ)')),
                ('cpf_cnpj', models.CharField(max_length=20, verbose_name='CPF ou CNPJ')),
                ('rg_ie', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG / Inscrição Estadual')),
                ('num_registro', models.IntegerField(blank=True, null=True, verbose_name='Nº Registro')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento / Fundação')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('celular', models.CharField(blank=True, max_length=20)),
                ('telefone_fixo', models.CharField(blank=True, max_length=20)),
                ('cep', models.CharField(blank=True, max_length=9)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('situacao', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=10)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_cadastros/')),
                ('observacoes', models.TextField(blank=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.categoriacliente', verbose_name='Categoria (Apenas Clientes)')),
            ],
            options={
                'verbose_name': 'Cadastro',
                'verbose_name_plural': 'Cadastros',
                'ordering': ['nome'],
                'unique_together': {('empresa', 'cpf_cnpj')},
            },
        ),
    ]
