# Generated by Django 5.2.8 on 2025-11-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='rg_ie',
        ),
        migrations.AddField(
            model_name='cadastro',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual (PJ ou Produtor Rural)'),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='is_produtor_rural',
            field=models.BooleanField(default=False, verbose_name='Produtor Rural?'),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG (Apenas PF)'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='razao_social',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Razão Social'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='tipo_pessoa',
            field=models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PF', max_length=2, verbose_name='Tipo de Pessoa'),
        ),
    ]
