# Generated by Django 5.2.8 on 2025-11-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='banner',
            field=models.ImageField(blank=True, help_text='Imagem de fundo da tela inicial', null=True, upload_to='empresas/banners/'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/logos/'),
        ),
    ]
