# Generated by Django 5.2.8 on 2025-11-25 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_empresa_banner_empresa_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(choices=[('CAIXA_PADRAO_ID', 'Financeiro - ID do Caixa Padrão'), ('TAXA_JUROS_MENSAL', 'Financeiro - Taxa de Juros Mensal (%)'), ('PLANO_CONTAS_MENSALIDADE_ID', 'Financeiro - ID Plano Contas (Mensalidade)'), ('PLANO_CONTAS_JUROS_ID', 'Financeiro - ID Plano Contas (Juros/Multa)')], max_length=100)),
                ('valor', models.CharField(help_text='Digite o ID ou o Valor correspondente', max_length=255)),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição / Notas')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Parâmetro do Sistema',
                'verbose_name_plural': 'Parâmetros do Sistema',
                'unique_together': {('empresa', 'chave')},
            },
        ),
    ]
