# Generated by Django 5.2.8 on 2026-07-19 22:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0002_remove_cadastro_rg_ie_cadastro_inscricao_estadual_and_more'),
        ('core', '0003_parametrosistema'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Grupo')),
                ('valor_diaria_padrao', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Diária Padrão (R$)')),
                ('valor_mensal_padrao', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Mensal Padrão (R$)')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Tipo de Veículo',
                'verbose_name_plural': 'Tipos de Veículos',
                'ordering': ['nome'],
                'unique_together': {('empresa', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, verbose_name='Placa')),
                ('renavam', models.CharField(blank=True, max_length=20, verbose_name='Renavam')),
                ('chassi', models.CharField(blank=True, max_length=20, verbose_name='Chassi')),
                ('marca', models.CharField(choices=[('CHEVROLET', 'Chevrolet'), ('FIAT', 'Fiat'), ('FORD', 'Ford'), ('HONDA', 'Honda'), ('HYUNDAI', 'Hyundai'), ('JEEP', 'Jeep'), ('KIA', 'Kia'), ('NISSAN', 'Nissan'), ('PEUGEOT', 'Peugeot'), ('RENAULT', 'Renault'), ('TOYOTA', 'Toyota'), ('VOLKSWAGEN', 'Volkswagen'), ('OUTRA', 'Outra')], max_length=20, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('ano_fabricacao', models.IntegerField(verbose_name='Ano Fabricação')),
                ('ano_modelo', models.IntegerField(blank=True, null=True, verbose_name='Ano Modelo')),
                ('cor', models.CharField(max_length=50, verbose_name='Cor')),
                ('km_atual', models.IntegerField(default=0, verbose_name='KM Atual')),
                ('nivel_tanque', models.IntegerField(default=8, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)], verbose_name='Nível do Tanque (0-8)')),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('ALUGADO', 'Alugado'), ('VENDIDO', 'Vendido'), ('MANUTENCAO', 'Em Manutenção')], default='DISPONIVEL', max_length=12)),
                ('valor_compra', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor de Compra (R$)')),
                ('valor_venda', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor de Venda (R$)')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='veiculos/')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locacao.tipoveiculo', verbose_name='Grupo/Tipo')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['marca', 'modelo'],
                'unique_together': {('empresa', 'placa')},
            },
        ),
        migrations.CreateModel(
            name='ManutencaoVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField(verbose_name='Data Entrada')),
                ('data_saida', models.DateField(blank=True, null=True, verbose_name='Data Saída')),
                ('tipo_servico', models.CharField(max_length=100, verbose_name='Tipo de Serviço')),
                ('descricao', models.TextField(verbose_name='Descrição do Serviço')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('oficina', models.CharField(blank=True, max_length=200, verbose_name='Oficina/Mecânico')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locacao.veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Manutenção de Veículo',
                'verbose_name_plural': 'Manutenções de Veículos',
                'ordering': ['-data_entrada'],
            },
        ),
        migrations.CreateModel(
            name='ContratoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(max_length=20, unique=True, verbose_name='Nº Contrato')),
                ('data_venda', models.DateField(verbose_name='Data da Venda')),
                ('valor_venda', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor da Venda (R$)')),
                ('forma_pagamento', models.CharField(choices=[('AVISTA', 'À Vista'), ('PIX', 'PIX'), ('CARTAO_CREDITO', 'Cartão de Crédito'), ('CARTAO_DEBITO', 'Cartão de Débito'), ('FINANCIADO', 'Financiado'), ('CREDIARIO', 'Crediário'), ('PERMUTA', 'Permuta')], default='AVISTA', max_length=20, verbose_name='Forma de Pagamento')),
                ('km_venda', models.IntegerField(default=0, verbose_name='KM na Venda')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=10)),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.cadastro', verbose_name='Cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locacao.veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Contrato de Venda',
                'verbose_name_plural': 'Contratos de Venda',
                'ordering': ['-data_venda'],
            },
        ),
        migrations.CreateModel(
            name='ContratoLocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(max_length=20, unique=True, verbose_name='Nº Contrato')),
                ('data_reserva', models.DateTimeField(auto_now_add=True, verbose_name='Data da Reserva')),
                ('data_saida', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora Saída')),
                ('data_retorno_prevista', models.DateTimeField(verbose_name='Data/Hora Retorno Previsto')),
                ('data_devolucao_real', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora Devolução Real')),
                ('local_retirada', models.CharField(default='Matriz', max_length=255, verbose_name='Local de Retirada')),
                ('local_devolucao', models.CharField(default='Matriz', max_length=255, verbose_name='Local de Devolução')),
                ('km_saida', models.IntegerField(default=0, verbose_name='KM Saída')),
                ('km_chegada', models.IntegerField(blank=True, null=True, verbose_name='KM Chegada')),
                ('tanque_saida', models.IntegerField(default=8, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)], verbose_name='Tanque Saída (0-8)')),
                ('tanque_chegada', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)], verbose_name='Tanque Chegada (0-8)')),
                ('valor_diaria', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Diária (R$)')),
                ('desconto_percentual', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Desconto (%)')),
                ('desconto_valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto (R$)')),
                ('protecao_casco', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Proteção Carro Casco (R$)')),
                ('premio_rcf', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prêmio Diário RCF (R$)')),
                ('limpeza_garantia', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Limpeza Garantia (R$)')),
                ('taxa_aluguel', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taxa de Aluguel (R$)')),
                ('valor_total_dia', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Valor Total Dia (R$)')),
                ('deposito_garantia', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Depósito em Garantia (R$)')),
                ('forma_pagamento', models.CharField(choices=[('AVISTA', 'À Vista'), ('PIX', 'PIX'), ('CARTAO_CREDITO', 'Cartão de Crédito'), ('CARTAO_DEBITO', 'Cartão de Débito'), ('CREDIARIO', 'Crediário'), ('BOLETO', 'Boleto')], default='AVISTA', max_length=20, verbose_name='Forma de Pagamento')),
                ('reserva_codigo', models.CharField(blank=True, max_length=20, verbose_name='Código da Reserva')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto (Reservado)'), ('ATIVO', 'Ativo (Veículo Retirado)'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=12)),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.cadastro', verbose_name='Cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locacao.veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Contrato de Locação',
                'verbose_name_plural': 'Contratos de Locação',
                'ordering': ['-data_reserva'],
            },
        ),
    ]
