# Generated by Django 5.2.8 on 2026-07-19 23:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratolocacao',
            name='km_saida',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='KM Saída'),
        ),
        migrations.AlterField(
            model_name='contratolocacao',
            name='tanque_saida',
            field=models.IntegerField(blank=True, default=8, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)], verbose_name='Tanque Saída (0-8)'),
        ),
    ]
