# Generated by Django 5.2.8 on 2026-07-19 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacao', '0002_alter_contratolocacao_km_saida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratolocacao',
            name='forma_pagamento_devolucao',
            field=models.CharField(blank=True, choices=[('AVISTA', 'À Vista'), ('PIX', 'PIX'), ('CARTAO_CREDITO', 'Cartão de Crédito'), ('CARTAO_DEBITO', 'Cartão de Débito'), ('CREDIARIO', 'Crediário'), ('BOLETO', 'Boleto')], max_length=20, null=True, verbose_name='Forma Pgto na Devolução'),
        ),
        migrations.AddField(
            model_name='contratolocacao',
            name='observacoes_financeiras',
            field=models.TextField(blank=True, verbose_name='Observações Financeiras'),
        ),
        migrations.AddField(
            model_name='contratolocacao',
            name='valor_desconto_devolucao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto na Devolução (R$)'),
        ),
        migrations.AddField(
            model_name='contratolocacao',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Pago (R$)'),
        ),
    ]
