# Generated by Django 5.2.8 on 2026-07-21 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_parametrosistema'),
        ('locacao', '0003_contratolocacao_forma_pagamento_devolucao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('celular', models.CharField(blank=True, max_length=20, verbose_name='Celular')),
                ('telefone_fixo', models.CharField(blank=True, max_length=20, verbose_name='Telefone Fixo')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('uf', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('matricula', models.CharField(blank=True, max_length=20, verbose_name='Matrícula')),
                ('comissao_percentual', models.DecimalField(decimal_places=2, default=0, help_text='Percentual de comissão sobre vendas', max_digits=5, verbose_name='Comissão Padrão (%)')),
                ('comissao_valor_fixo', models.DecimalField(decimal_places=2, default=0, help_text='Valor fixo por venda (se aplicável)', max_digits=10, verbose_name='Comissão Valor Fixo (R$)')),
                ('situacao', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=10)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='vendedores/')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('total_vendas', models.IntegerField(default=0, verbose_name='Total de Vendas')),
                ('valor_total_vendas', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Total em Vendas (R$)')),
                ('total_comissoes', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total de Comissões (R$)')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
                'ordering': ['nome'],
                'unique_together': {('empresa', 'cpf')},
            },
        ),
        migrations.CreateModel(
            name='ComissaoVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_venda', models.DateField(verbose_name='Data da Venda')),
                ('valor_venda', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor da Venda (R$)')),
                ('percentual_comissao', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Percentual (%)')),
                ('valor_comissao', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Comissão (R$)')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGA', 'Paga'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=10)),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('contrato_venda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locacao.contratovenda', verbose_name='Contrato de Venda')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locacao.vendedor', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Comissão de Vendedor',
                'verbose_name_plural': 'Comissões de Vendedores',
                'ordering': ['-data_venda'],
            },
        ),
    ]
