# Generated by Django 5.2.8 on 2026-07-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacao', '0004_vendedor_comissaovendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratolocacao',
            name='valor_total_locacao',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Valor Total da Locação (R$)'),
        ),
    ]
