# Generated by Django 5.2.8 on 2026-07-21 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacao', '0005_contratolocacao_valor_total_locacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratovenda',
            name='data_vencimento_primeira',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimento 1ª Parcela'),
        ),
        migrations.AddField(
            model_name='contratovenda',
            name='parcelas',
            field=models.PositiveIntegerField(default=1, verbose_name='Nº de Parcelas'),
        ),
        migrations.AddField(
            model_name='contratovenda',
            name='valor_entrada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor da Entrada (R$)'),
        ),
        migrations.AddField(
            model_name='contratovenda',
            name='valor_parcela',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor da Parcela (R$)'),
        ),
        migrations.AddField(
            model_name='contratovenda',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locacao.vendedor', verbose_name='Vendedor'),
        ),
    ]
