# Generated by Django 5.2.8 on 2026-07-22 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_parametrosistema'),
        ('locacao', '0006_contratovenda_data_vencimento_primeira_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manutencaoveiculo',
            name='contato_oficina',
            field=models.CharField(blank=True, max_length=50, verbose_name='Contato da Oficina'),
        ),
        migrations.AddField(
            model_name='manutencaoveiculo',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto (R$)'),
        ),
        migrations.AddField(
            model_name='manutencaoveiculo',
            name='garantia_ate',
            field=models.DateField(blank=True, null=True, verbose_name='Garantia até'),
        ),
        migrations.AddField(
            model_name='manutencaoveiculo',
            name='garantia_km',
            field=models.IntegerField(default=0, verbose_name='Garantia até KM'),
        ),
        migrations.AddField(
            model_name='manutencaoveiculo',
            name='garantia_servico',
            field=models.BooleanField(default=False, verbose_name='Serviço com Garantia'),
        ),
        migrations.AddField(
            model_name='manutencaoveiculo',
            name='km_na_manutencao',
            field=models.IntegerField(default=0, help_text='KM registrado no momento da manutenção', verbose_name='KM na Manutenção'),
        ),
        migrations.AddField(
            model_name='manutencaoveiculo',
            name='numero_nota_fiscal',
            field=models.CharField(blank=True, max_length=30, verbose_name='Nº Nota Fiscal'),
        ),
        migrations.AddField(
            model_name='manutencaoveiculo',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='manutencaoveiculo',
            name='pecas_utilizadas',
            field=models.TextField(blank=True, help_text='Liste as peças utilizadas nesta manutenção', verbose_name='Peças Utilizadas'),
        ),
        migrations.AddField(
            model_name='manutencaoveiculo',
            name='proximo_km_manutencao',
            field=models.IntegerField(default=0, help_text='KM previsto para a próxima manutenção deste tipo', verbose_name='Próximo KM de Manutenção'),
        ),
        migrations.AddField(
            model_name='manutencaoveiculo',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=12, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='manutencaoveiculo',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Valor Total (R$)'),
        ),
        migrations.AlterField(
            model_name='manutencaoveiculo',
            name='oficina',
            field=models.CharField(max_length=200, verbose_name='Oficina/Mecânico'),
        ),
        migrations.CreateModel(
            name='ProgramaManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servico', models.CharField(max_length=100, verbose_name='Tipo de Serviço')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ciclo', models.CharField(choices=[('KM', 'Por Quilometragem'), ('TEMPO', 'Por Tempo (dias)'), ('AMBOS', 'Por KM e Tempo')], default='KM', max_length=5, verbose_name='Ciclo de Manutenção')),
                ('km_intervalo', models.IntegerField(default=0, help_text='Ex: 5000 para troca de óleo a cada 5.000 km', verbose_name='Intervalo KM')),
                ('dias_intervalo', models.IntegerField(default=0, help_text='Ex: 180 para troca de óleo a cada 6 meses', verbose_name='Intervalo Dias')),
                ('valor_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Estimado (R$)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
                ('tipo_veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locacao.tipoveiculo', verbose_name='Tipo de Veículo')),
            ],
            options={
                'verbose_name': 'Programa de Manutenção',
                'verbose_name_plural': 'Programas de Manutenção',
                'ordering': ['tipo_veiculo', 'tipo_servico'],
            },
        ),
        migrations.AddField(
            model_name='manutencaoveiculo',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locacao.programamanutencao', verbose_name='Programa de Manutenção'),
        ),
    ]
