# Generated by Django 5.2.8 on 2025-11-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='documento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº Doc / Parcela'),
        ),
    ]
