# Generated by Django 5.2.8 on 2025-11-27 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_parametrosistema'),
        ('financeiro', '0002_conta_documento'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='planodecontas',
            unique_together={('empresa', 'codigo')},
        ),
    ]
